// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -513338516;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__compression__cancel_compression_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_compression",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::compression::cancel_compression();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__compression__compress_game_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compress_game",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_game_path = <String>::sse_decode(&mut deserializer);
            let api_game_name = <String>::sse_decode(&mut deserializer);
            let api_algorithm =
                <crate::api::types::FrbCompressionAlgorithm>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::types::FrbCompressionProgress,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbCompressionError>((move || {
                    let output_ok = crate::api::compression::compress_game(
                        api_game_path,
                        api_game_name,
                        api_algorithm,
                        api_sink,
                    )?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__compression__decompress_game_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "decompress_game",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_game_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbCompressionError>((move || {
                    let output_ok = crate::api::compression::decompress_game(api_game_path)?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__discovery__get_all_games_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_all_games",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbDiscoveryError>((move || {
                    let output_ok = crate::api::discovery::get_all_games()?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__discovery__get_all_games_quick_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_all_games_quick",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbDiscoveryError>((move || {
                    let output_ok = crate::api::discovery::get_all_games_quick()?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__compression__get_compression_progress_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_compression_progress",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::compression::get_compression_progress())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__compression__get_compression_ratio_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_compression_ratio",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_folder_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbCompressionError>((move || {
                    let output_ok =
                        crate::api::compression::get_compression_ratio(api_folder_path)?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__discovery__hydrate_game_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "hydrate_game",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_platform = <crate::api::types::FrbPlatform>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbDiscoveryError>((move || {
                    let output_ok =
                        crate::api::discovery::hydrate_game(api_path, api_name, api_platform)?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__minimal__init_app_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::minimal::init_app())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__automation__is_auto_compression_running_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_auto_compression_running",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::automation::is_auto_compression_running())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__compression__is_directstorage_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_directstorage",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_game_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::compression::is_directstorage(api_game_path))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__discovery__scan_custom_folder_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scan_custom_folder",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbDiscoveryError>((move || {
                    let output_ok = crate::api::discovery::scan_custom_folder(api_path)?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__automation__start_auto_compression_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_auto_compression",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::types::FrbAutomationError>((move || {
                    let output_ok = crate::api::automation::start_auto_compression()?;
                    Ok(output_ok)
                })(
                ))
            }
        },
    )
}
fn wire__crate__api__automation__stop_auto_compression_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_auto_compression",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::api::types::FrbAutomationError>((move || {
                let output_ok = crate::api::automation::stop_auto_compression()?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::types::FrbCompressionProgress,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::types::FrbAutomationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::types::FrbAutomationError::AlreadyRunning;
            }
            1 => {
                return crate::api::types::FrbAutomationError::NotRunning;
            }
            2 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbAutomationError::StartFailed {
                    message: var_message,
                };
            }
            3 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbAutomationError::StopFailed {
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::FrbCompressionAlgorithm {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::FrbCompressionAlgorithm::Xpress4K,
            1 => crate::api::types::FrbCompressionAlgorithm::Xpress8K,
            2 => crate::api::types::FrbCompressionAlgorithm::Xpress16K,
            3 => crate::api::types::FrbCompressionAlgorithm::Lzx,
            _ => unreachable!("Invalid variant for FrbCompressionAlgorithm: {}", inner),
        };
    }
}

impl SseDecode for crate::api::types::FrbCompressionError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::types::FrbCompressionError::LockedFile { path: var_path };
            }
            1 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::types::FrbCompressionError::PermissionDenied { path: var_path };
            }
            2 => {
                return crate::api::types::FrbCompressionError::DiskFull;
            }
            3 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::types::FrbCompressionError::PathNotFound { path: var_path };
            }
            4 => {
                let mut var_path = <String>::sse_decode(deserializer);
                return crate::api::types::FrbCompressionError::NotADirectory { path: var_path };
            }
            5 => {
                return crate::api::types::FrbCompressionError::GameRunning;
            }
            6 => {
                return crate::api::types::FrbCompressionError::DirectStorageDetected;
            }
            7 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbCompressionError::WofApiError {
                    message: var_message,
                };
            }
            8 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbCompressionError::IoError {
                    message: var_message,
                };
            }
            9 => {
                return crate::api::types::FrbCompressionError::Cancelled;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::FrbCompressionProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_gameName = <String>::sse_decode(deserializer);
        let mut var_filesTotal = <u64>::sse_decode(deserializer);
        let mut var_filesProcessed = <u64>::sse_decode(deserializer);
        let mut var_bytesOriginal = <u64>::sse_decode(deserializer);
        let mut var_bytesCompressed = <u64>::sse_decode(deserializer);
        let mut var_bytesSaved = <u64>::sse_decode(deserializer);
        let mut var_estimatedTimeRemainingMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_isComplete = <bool>::sse_decode(deserializer);
        return crate::api::types::FrbCompressionProgress {
            game_name: var_gameName,
            files_total: var_filesTotal,
            files_processed: var_filesProcessed,
            bytes_original: var_bytesOriginal,
            bytes_compressed: var_bytesCompressed,
            bytes_saved: var_bytesSaved,
            estimated_time_remaining_ms: var_estimatedTimeRemainingMs,
            is_complete: var_isComplete,
        };
    }
}

impl SseDecode for crate::api::types::FrbCompressionStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_originalBytes = <u64>::sse_decode(deserializer);
        let mut var_compressedBytes = <u64>::sse_decode(deserializer);
        let mut var_filesProcessed = <u64>::sse_decode(deserializer);
        let mut var_filesSkipped = <u64>::sse_decode(deserializer);
        let mut var_durationMs = <u64>::sse_decode(deserializer);
        return crate::api::types::FrbCompressionStats {
            original_bytes: var_originalBytes,
            compressed_bytes: var_compressedBytes,
            files_processed: var_filesProcessed,
            files_skipped: var_filesSkipped,
            duration_ms: var_durationMs,
        };
    }
}

impl SseDecode for crate::api::types::FrbDiscoveryError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbDiscoveryError::DiscoveryFailed {
                    message: var_message,
                };
            }
            1 => {
                let mut var_path = <String>::sse_decode(deserializer);
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbDiscoveryError::CustomScanFailed {
                    path: var_path,
                    message: var_message,
                };
            }
            2 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::types::FrbDiscoveryError::InvalidPath {
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::FrbGameInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_platform = <crate::api::types::FrbPlatform>::sse_decode(deserializer);
        let mut var_sizeBytes = <u64>::sse_decode(deserializer);
        let mut var_compressedSize = <Option<u64>>::sse_decode(deserializer);
        let mut var_isCompressed = <bool>::sse_decode(deserializer);
        let mut var_isDirectstorage = <bool>::sse_decode(deserializer);
        let mut var_excluded = <bool>::sse_decode(deserializer);
        let mut var_lastPlayed = <Option<i64>>::sse_decode(deserializer);
        return crate::api::types::FrbGameInfo {
            name: var_name,
            path: var_path,
            platform: var_platform,
            size_bytes: var_sizeBytes,
            compressed_size: var_compressedSize,
            is_compressed: var_isCompressed,
            is_directstorage: var_isDirectstorage,
            excluded: var_excluded,
            last_played: var_lastPlayed,
        };
    }
}

impl SseDecode for crate::api::types::FrbPlatform {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::FrbPlatform::Steam,
            1 => crate::api::types::FrbPlatform::EpicGames,
            2 => crate::api::types::FrbPlatform::GogGalaxy,
            3 => crate::api::types::FrbPlatform::UbisoftConnect,
            4 => crate::api::types::FrbPlatform::EaApp,
            5 => crate::api::types::FrbPlatform::BattleNet,
            6 => crate::api::types::FrbPlatform::XboxGamePass,
            7 => crate::api::types::FrbPlatform::Custom,
            _ => unreachable!("Invalid variant for FrbPlatform: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::types::FrbGameInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::FrbGameInfo>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::types::FrbCompressionProgress> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::types::FrbCompressionProgress>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::types::FrbGameInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::types::FrbGameInfo>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__compression__compress_game_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__compression__decompress_game_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__discovery__get_all_games_impl(port, ptr, rust_vec_len, data_len),
        5 => {
            wire__crate__api__discovery__get_all_games_quick_impl(port, ptr, rust_vec_len, data_len)
        }
        7 => wire__crate__api__compression__get_compression_ratio_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__api__discovery__hydrate_game_impl(port, ptr, rust_vec_len, data_len),
        12 => {
            wire__crate__api__discovery__scan_custom_folder_impl(port, ptr, rust_vec_len, data_len)
        }
        13 => wire__crate__api__automation__start_auto_compression_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__compression__cancel_compression_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__compression__get_compression_progress_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__minimal__init_app_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__automation__is_auto_compression_running_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => wire__crate__api__compression__is_directstorage_impl(ptr, rust_vec_len, data_len),
        14 => wire__crate__api__automation__stop_auto_compression_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbAutomationError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::FrbAutomationError::AlreadyRunning => [0.into_dart()].into_dart(),
            crate::api::types::FrbAutomationError::NotRunning => [1.into_dart()].into_dart(),
            crate::api::types::FrbAutomationError::StartFailed { message } => {
                [2.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbAutomationError::StopFailed { message } => {
                [3.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbAutomationError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbAutomationError>
    for crate::api::types::FrbAutomationError
{
    fn into_into_dart(self) -> crate::api::types::FrbAutomationError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbCompressionAlgorithm {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Xpress4K => 0.into_dart(),
            Self::Xpress8K => 1.into_dart(),
            Self::Xpress16K => 2.into_dart(),
            Self::Lzx => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbCompressionAlgorithm
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbCompressionAlgorithm>
    for crate::api::types::FrbCompressionAlgorithm
{
    fn into_into_dart(self) -> crate::api::types::FrbCompressionAlgorithm {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbCompressionError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::FrbCompressionError::LockedFile { path } => {
                [0.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::PermissionDenied { path } => {
                [1.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::DiskFull => [2.into_dart()].into_dart(),
            crate::api::types::FrbCompressionError::PathNotFound { path } => {
                [3.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::NotADirectory { path } => {
                [4.into_dart(), path.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::GameRunning => [5.into_dart()].into_dart(),
            crate::api::types::FrbCompressionError::DirectStorageDetected => {
                [6.into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::WofApiError { message } => {
                [7.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::IoError { message } => {
                [8.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbCompressionError::Cancelled => [9.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbCompressionError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbCompressionError>
    for crate::api::types::FrbCompressionError
{
    fn into_into_dart(self) -> crate::api::types::FrbCompressionError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbCompressionProgress {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.game_name.into_into_dart().into_dart(),
            self.files_total.into_into_dart().into_dart(),
            self.files_processed.into_into_dart().into_dart(),
            self.bytes_original.into_into_dart().into_dart(),
            self.bytes_compressed.into_into_dart().into_dart(),
            self.bytes_saved.into_into_dart().into_dart(),
            self.estimated_time_remaining_ms
                .into_into_dart()
                .into_dart(),
            self.is_complete.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbCompressionProgress
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbCompressionProgress>
    for crate::api::types::FrbCompressionProgress
{
    fn into_into_dart(self) -> crate::api::types::FrbCompressionProgress {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbCompressionStats {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.original_bytes.into_into_dart().into_dart(),
            self.compressed_bytes.into_into_dart().into_dart(),
            self.files_processed.into_into_dart().into_dart(),
            self.files_skipped.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbCompressionStats
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbCompressionStats>
    for crate::api::types::FrbCompressionStats
{
    fn into_into_dart(self) -> crate::api::types::FrbCompressionStats {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbDiscoveryError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::FrbDiscoveryError::DiscoveryFailed { message } => {
                [0.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::FrbDiscoveryError::CustomScanFailed { path, message } => [
                1.into_dart(),
                path.into_into_dart().into_dart(),
                message.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::FrbDiscoveryError::InvalidPath { message } => {
                [2.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbDiscoveryError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbDiscoveryError>
    for crate::api::types::FrbDiscoveryError
{
    fn into_into_dart(self) -> crate::api::types::FrbDiscoveryError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbGameInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.platform.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.compressed_size.into_into_dart().into_dart(),
            self.is_compressed.into_into_dart().into_dart(),
            self.is_directstorage.into_into_dart().into_dart(),
            self.excluded.into_into_dart().into_dart(),
            self.last_played.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbGameInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbGameInfo>
    for crate::api::types::FrbGameInfo
{
    fn into_into_dart(self) -> crate::api::types::FrbGameInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FrbPlatform {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Steam => 0.into_dart(),
            Self::EpicGames => 1.into_dart(),
            Self::GogGalaxy => 2.into_dart(),
            Self::UbisoftConnect => 3.into_dart(),
            Self::EaApp => 4.into_dart(),
            Self::BattleNet => 5.into_dart(),
            Self::XboxGamePass => 6.into_dart(),
            Self::Custom => 7.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FrbPlatform
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FrbPlatform>
    for crate::api::types::FrbPlatform
{
    fn into_into_dart(self) -> crate::api::types::FrbPlatform {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::types::FrbCompressionProgress,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::types::FrbAutomationError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::FrbAutomationError::AlreadyRunning => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::types::FrbAutomationError::NotRunning => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::types::FrbAutomationError::StartFailed { message } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::types::FrbAutomationError::StopFailed { message } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::FrbCompressionAlgorithm {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::FrbCompressionAlgorithm::Xpress4K => 0,
                crate::api::types::FrbCompressionAlgorithm::Xpress8K => 1,
                crate::api::types::FrbCompressionAlgorithm::Xpress16K => 2,
                crate::api::types::FrbCompressionAlgorithm::Lzx => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::types::FrbCompressionError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::FrbCompressionError::LockedFile { path } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::types::FrbCompressionError::PermissionDenied { path } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::types::FrbCompressionError::DiskFull => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::types::FrbCompressionError::PathNotFound { path } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::types::FrbCompressionError::NotADirectory { path } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(path, serializer);
            }
            crate::api::types::FrbCompressionError::GameRunning => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::types::FrbCompressionError::DirectStorageDetected => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::types::FrbCompressionError::WofApiError { message } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::types::FrbCompressionError::IoError { message } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::types::FrbCompressionError::Cancelled => {
                <i32>::sse_encode(9, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::FrbCompressionProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.game_name, serializer);
        <u64>::sse_encode(self.files_total, serializer);
        <u64>::sse_encode(self.files_processed, serializer);
        <u64>::sse_encode(self.bytes_original, serializer);
        <u64>::sse_encode(self.bytes_compressed, serializer);
        <u64>::sse_encode(self.bytes_saved, serializer);
        <Option<i64>>::sse_encode(self.estimated_time_remaining_ms, serializer);
        <bool>::sse_encode(self.is_complete, serializer);
    }
}

impl SseEncode for crate::api::types::FrbCompressionStats {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.original_bytes, serializer);
        <u64>::sse_encode(self.compressed_bytes, serializer);
        <u64>::sse_encode(self.files_processed, serializer);
        <u64>::sse_encode(self.files_skipped, serializer);
        <u64>::sse_encode(self.duration_ms, serializer);
    }
}

impl SseEncode for crate::api::types::FrbDiscoveryError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::FrbDiscoveryError::DiscoveryFailed { message } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::types::FrbDiscoveryError::CustomScanFailed { path, message } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(path, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::types::FrbDiscoveryError::InvalidPath { message } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::FrbGameInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.path, serializer);
        <crate::api::types::FrbPlatform>::sse_encode(self.platform, serializer);
        <u64>::sse_encode(self.size_bytes, serializer);
        <Option<u64>>::sse_encode(self.compressed_size, serializer);
        <bool>::sse_encode(self.is_compressed, serializer);
        <bool>::sse_encode(self.is_directstorage, serializer);
        <bool>::sse_encode(self.excluded, serializer);
        <Option<i64>>::sse_encode(self.last_played, serializer);
    }
}

impl SseEncode for crate::api::types::FrbPlatform {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::FrbPlatform::Steam => 0,
                crate::api::types::FrbPlatform::EpicGames => 1,
                crate::api::types::FrbPlatform::GogGalaxy => 2,
                crate::api::types::FrbPlatform::UbisoftConnect => 3,
                crate::api::types::FrbPlatform::EaApp => 4,
                crate::api::types::FrbPlatform::BattleNet => 5,
                crate::api::types::FrbPlatform::XboxGamePass => 6,
                crate::api::types::FrbPlatform::Custom => 7,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::types::FrbGameInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::FrbGameInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::types::FrbCompressionProgress> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::types::FrbCompressionProgress>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::types::FrbGameInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::types::FrbGameInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
